In [1]:
import tensorflow as tf

In [3]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [4]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [5]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  49682.555 
Prediction:
 [[-49.308823]
 [-51.254364]
 [-54.868603]
 [-57.09406 ]
 [-39.24999 ]]
10 Cost:  4.2251124 
Prediction:
 [[147.86618]
 [185.72557]
 [178.63687]
 [197.18625]
 [141.50468]]
20 Cost:  3.760891 
Prediction:
 [[148.46793]
 [186.43915]
 [179.34508]
 [197.95616]
 [142.04764]]
30 Cost:  3.7515442 
Prediction:
 [[148.47487]
 [186.43785]
 [179.34888]
 [197.95901]
 [142.04533]]
40 Cost:  3.742228 
Prediction:
 [[148.48001]
 [186.43442]
 [179.35056]
 [197.95953]
 [142.04138]]
50 Cost:  3.7329555 
Prediction:
 [[148.48514]
 [186.43097]
 [179.3522 ]
 [197.96005]
 [142.03745]]
60 Cost:  3.7237446 
Prediction:
 [[148.49025]
 [186.42755]
 [179.35385]
 [197.96057]
 [142.03351]]
70 Cost:  3.71459 
Prediction:
 [[148.49533]
 [186.42412]
 [179.3555 ]
 [197.96109]
 [142.0296 ]]
80 Cost:  3.7054334 
Prediction:
 [[148.50043]
 [186.4207 ]
 [179.35715]
 [197.9616 ]
 [142.02568]]
90 Cost:  3.6963716 
Prediction:
 [[148.5055 ]
 [186.41731]
 [179.3588 ]
 [197.96211]
 [142.0218 ]]


1550 Cost:  2.742117 
Prediction:
 [[149.12314]
 [186.00378]
 [179.56062]
 [198.01035]
 [141.56168]]
1560 Cost:  2.7375228 
Prediction:
 [[149.12665]
 [186.00145]
 [179.5618 ]
 [198.01053]
 [141.55919]]
1570 Cost:  2.732983 
Prediction:
 [[149.13011]
 [185.99911]
 [179.56291]
 [198.01068]
 [141.55667]]
1580 Cost:  2.7284276 
Prediction:
 [[149.13359]
 [185.99678]
 [179.56406]
 [198.01083]
 [141.55417]]
1590 Cost:  2.7239406 
Prediction:
 [[149.13705]
 [185.99448]
 [179.56522]
 [198.01103]
 [141.5517 ]]
1600 Cost:  2.7194247 
Prediction:
 [[149.14053]
 [185.99219]
 [179.56638]
 [198.0112 ]
 [141.54924]]
1610 Cost:  2.7149734 
Prediction:
 [[149.14397]
 [185.98988]
 [179.5675 ]
 [198.01137]
 [141.54677]]
1620 Cost:  2.7104993 
Prediction:
 [[149.14742]
 [185.98758]
 [179.56863]
 [198.01152]
 [141.54431]]
1630 Cost:  2.7060654 
Prediction:
 [[149.15085]
 [185.98529]
 [179.56978]
 [198.01169]
 [141.54187]]
1640 Cost:  2.7016587 
Prediction:
 [[149.15428]
 [185.98302]
 [179.57092]
 [198.011