In [1]:
import tensorflow as tf
import numpy as np

In [2]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [ 42.]
 [101.]]


In [3]:
tf.set_random_seed(777)  # for reproducibility

In [4]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [5]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  17898.736 
Prediction:
 [[22.048063 ]
 [21.619787 ]
 [24.096693 ]
 [22.293005 ]
 [18.633902 ]
 [ 7.2669735]]
10 Cost:  1446.16 
Prediction:
 [[141.6899  ]
 [165.34758 ]
 [165.7506  ]
 [176.56352 ]
 [128.2332  ]
 [ 88.059494]]
20 Cost:  1443.5807 
Prediction:
 [[142.56464]
 [166.28539]
 [166.73271]
 [177.63895]
 [128.91528]
 [ 88.55791]]
30 Cost:  1441.7643 
Prediction:
 [[142.63483 ]
 [166.25623 ]
 [166.76205 ]
 [177.67679 ]
 [128.85986 ]
 [ 88.512726]]
40 Cost:  1439.9565 
Prediction:
 [[142.69936 ]
 [166.22063 ]
 [166.78484 ]
 [177.70755 ]
 [128.79959 ]
 [ 88.464066]]
50 Cost:  1438.1576 
Prediction:
 [[142.76363 ]
 [166.18515 ]
 [166.80753 ]
 [177.73824 ]
 [128.73947 ]
 [ 88.415596]]
60 Cost:  1436.3667 
Prediction:
 [[142.82767]
 [166.14973]
 [166.83008]
 [177.76883]
 [128.67946]
 [ 88.3673 ]]
70 Cost:  1434.5846 
Prediction:
 [[142.89148]
 [166.11441]
 [166.85258]
 [177.79935]
 [128.61961]
 [ 88.31922]]
80 Cost:  1432.8107 
Prediction:
 [[142.95508]
 [166.07922]
 [166.874

760 Cost:  1329.3064 
Prediction:
 [[146.80928 ]
 [163.92024 ]
 [168.21127 ]
 [179.76181 ]
 [124.82532 ]
 [ 85.448395]]
770 Cost:  1328.0011 
Prediction:
 [[146.85956]
 [163.89171]
 [168.2284 ]
 [179.78835]
 [124.77483]
 [ 85.41277]]
780 Cost:  1326.7019 
Prediction:
 [[146.90967 ]
 [163.86324 ]
 [168.24542 ]
 [179.81479 ]
 [124.724464]
 [ 85.3773  ]]
790 Cost:  1325.4083 
Prediction:
 [[146.95958]
 [163.83482]
 [168.26237]
 [179.84117]
 [124.67422]
 [ 85.34197]]
800 Cost:  1324.1194 
Prediction:
 [[147.00932 ]
 [163.80653 ]
 [168.27928 ]
 [179.86754 ]
 [124.624084]
 [ 85.306816]]
810 Cost:  1322.8365 
Prediction:
 [[147.05891]
 [163.77834]
 [168.29613]
 [179.89384]
 [124.5741 ]
 [ 85.27182]]
820 Cost:  1321.5583 
Prediction:
 [[147.10835]
 [163.7502 ]
 [168.3129 ]
 [179.92009]
 [124.52419]
 [ 85.23695]]
830 Cost:  1320.2854 
Prediction:
 [[147.15761]
 [163.72215]
 [168.3296 ]
 [179.94627]
 [124.47441]
 [ 85.20226]]
840 Cost:  1319.0181 
Prediction:
 [[147.20668]
 [163.69417]
 [168.346

1560 Cost:  1239.6235 
Prediction:
 [[150.33261 ]
 [161.88437 ]
 [169.38277 ]
 [181.7318  ]
 [121.134285]
 [ 83.05323 ]]
1570 Cost:  1238.6627 
Prediction:
 [[150.37079]
 [161.86185]
 [169.3951 ]
 [181.75464]
 [121.09224]
 [ 83.02861]]
1580 Cost:  1237.705 
Prediction:
 [[150.40884 ]
 [161.83939 ]
 [169.40738 ]
 [181.77745 ]
 [121.050285]
 [ 83.00411 ]]
1590 Cost:  1236.7511 
Prediction:
 [[150.4468  ]
 [161.81699 ]
 [169.41962 ]
 [181.80022 ]
 [121.008446]
 [ 82.979744]]
1600 Cost:  1235.8002 
Prediction:
 [[150.4846  ]
 [161.79466 ]
 [169.4318  ]
 [181.82294 ]
 [120.966675]
 [ 82.95549 ]]
1610 Cost:  1234.8523 
Prediction:
 [[150.52226 ]
 [161.77238 ]
 [169.44392 ]
 [181.84563 ]
 [120.924995]
 [ 82.93135 ]]
1620 Cost:  1233.9077 
Prediction:
 [[150.55981 ]
 [161.75021 ]
 [169.45601 ]
 [181.86827 ]
 [120.883415]
 [ 82.90733 ]]
1630 Cost:  1232.967 
Prediction:
 [[150.59726]
 [161.72806]
 [169.46805]
 [181.89087]
 [120.84194]
 [ 82.88343]]
1640 Cost:  1232.0287 
Prediction:
 [[150.6345

In [7]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

Your score will be  [[115.34557]]


In [8]:
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Other scores will be  [[132.53267]
 [190.98846]]
