In [1]:
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [4]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [5]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  118169.36 
Prediction:
 [-142.65477 -189.28717 -177.05307 -194.66486 -147.5316 ]
10 Cost:  58.582436 
Prediction:
 [161.33508 176.14162 182.9812  197.40666 131.20967]
20 Cost:  57.19158 
Prediction:
 [162.22557 177.26738 184.06157 198.58641 132.0795 ]
30 Cost:  56.883583 
Prediction:
 [162.19899 177.2908  184.05588 198.58342 132.10846]
40 Cost:  56.57719 
Prediction:
 [162.16975 177.31088 184.04694 198.57692 132.13484]
50 Cost:  56.272644 
Prediction:
 [162.14061 177.33089 184.03801 198.57043 132.16113]
60 Cost:  55.969666 
Prediction:
 [162.11151 177.35081 184.02908 198.56392 132.18733]
70 Cost:  55.668324 
Prediction:
 [162.08252 177.37071 184.02023 198.55745 132.2135 ]
80 Cost:  55.368492 
Prediction:
 [162.05357 177.39055 184.01134 198.55096 132.23956]
90 Cost:  55.070393 
Prediction:
 [162.02472 177.41032 184.00252 198.54454 132.26558]
100 Cost:  54.773792 
Prediction:
 [161.99596 177.43008 183.99373 198.53812 132.29153]
110 Cost:  54.479095 
Prediction:
 [161.96729 177.4

1280 Cost:  28.99618 
Prediction:
 [159.09444 179.4198  183.10544 197.88939 134.90791]
1290 Cost:  28.840631 
Prediction:
 [159.07361 179.43408 183.09903 197.88472 134.9267 ]
1300 Cost:  28.685917 
Prediction:
 [159.05283 179.44833 183.09268 197.88007 134.94543]
1310 Cost:  28.531961 
Prediction:
 [159.0321  179.46254 183.08632 197.87541 134.96414]
1320 Cost:  28.378864 
Prediction:
 [159.01143 179.47673 183.08002 197.8708  134.98279]
1330 Cost:  28.226648 
Prediction:
 [158.99081 179.49086 183.07372 197.86618 135.00137]
1340 Cost:  28.075306 
Prediction:
 [158.97029 179.50496 183.06743 197.8616  135.01993]
1350 Cost:  27.924683 
Prediction:
 [158.94977 179.519   183.06114 197.85698 135.0384 ]
1360 Cost:  27.774902 
Prediction:
 [158.92934 179.53304 183.05489 197.85243 135.05685]
1370 Cost:  27.625904 
Prediction:
 [158.90892 179.547   183.04865 197.84785 135.07524]
1380 Cost:  27.477692 
Prediction:
 [158.88861 179.56097 183.04242 197.8433  135.0936 ]
1390 Cost:  27.330402 
Prediction