In [1]:
import tensorflow as tf

In [2]:
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
# one-hot encoding: 
# 1, 0, 0 means 0
# 0, 1, 0 means 1
# 0, 0, 1 means 2 here
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])  # label의 갯수
nb_classes = 3  # class의 갯수

In [3]:
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
# hypothesis == Y hat: 예측값
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Y: 실제값
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [8]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
            
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.arg_max(a, 1)))

    print('--------------------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.arg_max(b, 1)))

    print('--------------------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.arg_max(c, 1)))

    print('--------------------------')

    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    # arg_max(input, dimension): input arry에 있는 놈들 중 최강자의 레이블 번호를 알려줌 (첫 번째 축을 중심으로(?))
    print(all, sess.run(tf.arg_max(all, 1)))

0 6.35413
200 0.49730197
400 0.3898974
600 0.29491794
800 0.23247069
1000 0.2101923
1200 0.19184625
1400 0.17642328
1600 0.16326189
1800 0.15189496
2000 0.1419788
[[2.118300e-03 9.978720e-01 9.770321e-06]] [1]
--------------------------
[[0.897284   0.0850395  0.01767655]] [0]
--------------------------
[[5.8797576e-09 2.6554661e-04 9.9973446e-01]] [2]
--------------------------
[[2.1182948e-03 9.9787199e-01 9.7703023e-06]
 [8.9728403e-01 8.5039474e-02 1.7676545e-02]
 [5.8797576e-09 2.6554661e-04 9.9973446e-01]] [1 0 2]
