In [3]:
import tensorflow as tf
import numpy as np
# from sklearn.preprocessing import MinMaxScaler

In [4]:
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [9]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
xy = min_max_scaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [10]:
type(xy)

numpy.ndarray

In [11]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [12]:
type(x_data)

numpy.ndarray

In [14]:
print(x_data)
print(y_data)

[[0.99999999 0.99999999 0.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782]
 [0.54412549 0.50274824 0.57608696 0.606468  ]
 [0.33890353 0.31368023 0.10869565 0.45989134]
 [0.51436    0.42582389 0.30434783 0.58504805]
 [0.49556179 0.42582389 0.31521739 0.48131134]
 [0.11436064 0.         0.20652174 0.22007776]
 [0.         0.07747099 0.5326087  0.        ]]
[[1.        ]
 [0.83755791]
 [0.6606331 ]
 [0.43800918]
 [0.42624401]
 [0.49276137]
 [0.18597238]
 [0.        ]]


In [16]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, [None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-3)
train = optimizer.minimize(cost)

In [17]:
print(x_data.shape)
print(W.shape)
print(b.shape)
print(y_data.shape)

(8, 4)
(4, 1)
(1,)
(8, 1)


In [10]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.73971415 
Prediction:
 [[1.6625015]
 [1.1981244]
 [1.2672242]
 [1.3654839]
 [1.3312224]
 [1.365667 ]
 [1.2220696]
 [1.2108619]]
1 Cost:  0.7396711 
Prediction:
 [[1.6624653]
 [1.1980885]
 [1.2671937]
 [1.3654594]
 [1.3311943]
 [1.3656397]
 [1.2220497]
 [1.2108421]]
2 Cost:  0.7396281 
Prediction:
 [[1.6624293]
 [1.1980526]
 [1.2671632]
 [1.3654351]
 [1.3311661]
 [1.3656123]
 [1.2220298]
 [1.2108222]]
3 Cost:  0.73958504 
Prediction:
 [[1.6623933]
 [1.1980166]
 [1.2671326]
 [1.3654106]
 [1.3311379]
 [1.3655849]
 [1.2220099]
 [1.2108024]]
4 Cost:  0.739542 
Prediction:
 [[1.6623573]
 [1.1979809]
 [1.2671021]
 [1.3653862]
 [1.3311096]
 [1.3655574]
 [1.2219899]
 [1.2107825]]
5 Cost:  0.7394991 
Prediction:
 [[1.6623213]
 [1.1979449]
 [1.2670717]
 [1.3653618]
 [1.3310815]
 [1.3655301]
 [1.22197  ]
 [1.2107627]]
6 Cost:  0.73945594 
Prediction:
 [[1.6622852]
 [1.197909 ]
 [1.2670411]
 [1.3653374]
 [1.3310533]
 [1.3655027]
 [1.22195  ]
 [1.2107428]]
7 Cost:  0.739413 
Prediction:
 

293 Cost:  0.7272401 
Prediction:
 [[1.6520009]
 [1.18766  ]
 [1.2583312]
 [1.3583654]
 [1.3230021]
 [1.357683 ]
 [1.2162588]
 [1.2050687]]
294 Cost:  0.7271979 
Prediction:
 [[1.6519651]
 [1.1876245]
 [1.258301 ]
 [1.3583412]
 [1.3229742]
 [1.3576558]
 [1.216239 ]
 [1.205049 ]]
295 Cost:  0.7271557 
Prediction:
 [[1.6519295]
 [1.1875889]
 [1.2582707]
 [1.358317 ]
 [1.3229462]
 [1.3576286]
 [1.2162192]
 [1.2050292]]
296 Cost:  0.7271135 
Prediction:
 [[1.6518939]
 [1.1875533]
 [1.2582406]
 [1.3582928]
 [1.3229183]
 [1.3576014]
 [1.2161994]
 [1.2050096]]
297 Cost:  0.72707134 
Prediction:
 [[1.6518581]
 [1.1875178]
 [1.2582103]
 [1.3582686]
 [1.3228904]
 [1.3575742]
 [1.2161796]
 [1.2049899]]
298 Cost:  0.7270292 
Prediction:
 [[1.6518224]
 [1.1874821]
 [1.2581801]
 [1.3582444]
 [1.3228624]
 [1.3575472]
 [1.2161599]
 [1.2049702]]
299 Cost:  0.726987 
Prediction:
 [[1.6517868]
 [1.1874466]
 [1.2581499]
 [1.3582202]
 [1.3228345]
 [1.35752  ]
 [1.2161402]
 [1.2049505]]
300 Cost:  0.7269448

590 Cost:  0.7148739 
Prediction:
 [[1.6414819]
 [1.1771747]
 [1.2494191]
 [1.3512297]
 [1.3147635]
 [1.3496805]
 [1.2104309]
 [1.1992579]]
591 Cost:  0.7148328 
Prediction:
 [[1.6414466]
 [1.1771396]
 [1.2493893]
 [1.3512058]
 [1.314736 ]
 [1.3496538]
 [1.2104113]
 [1.1992383]]
592 Cost:  0.7147918 
Prediction:
 [[1.6414115]
 [1.1771046]
 [1.2493596]
 [1.351182 ]
 [1.3147085]
 [1.3496271]
 [1.2103919]
 [1.199219 ]]
593 Cost:  0.71475065 
Prediction:
 [[1.6413764]
 [1.1770695]
 [1.2493298]
 [1.3511581]
 [1.3146809]
 [1.3496003]
 [1.2103724]
 [1.1991996]]
594 Cost:  0.71470946 
Prediction:
 [[1.6413412]
 [1.1770345]
 [1.2492999]
 [1.3511343]
 [1.3146534]
 [1.3495736]
 [1.2103529]
 [1.1991801]]
595 Cost:  0.71466845 
Prediction:
 [[1.641306 ]
 [1.1769994]
 [1.2492702]
 [1.3511105]
 [1.3146259]
 [1.3495469]
 [1.2103335]
 [1.1991607]]
596 Cost:  0.71462727 
Prediction:
 [[1.6412709]
 [1.1769644]
 [1.2492404]
 [1.3510866]
 [1.3145983]
 [1.3495201]
 [1.2103139]
 [1.1991413]]
597 Cost:  0.714

882 Cost:  0.7029844 
Prediction:
 [[1.6312639]
 [1.1669863]
 [1.2407576]
 [1.3442924]
 [1.306756 ]
 [1.3419024]
 [1.2047615]
 [1.1936044]]
883 Cost:  0.7029441 
Prediction:
 [[1.631229 ]
 [1.1669517]
 [1.240728 ]
 [1.3442687]
 [1.3067286]
 [1.3418759]
 [1.2047422]
 [1.1935852]]
884 Cost:  0.7029038 
Prediction:
 [[1.6311944]
 [1.166917 ]
 [1.2406986]
 [1.3442451]
 [1.3067014]
 [1.3418493]
 [1.2047228]
 [1.1935658]]
885 Cost:  0.7028636 
Prediction:
 [[1.6311595]
 [1.1668823]
 [1.240669 ]
 [1.3442215]
 [1.3066741]
 [1.3418229]
 [1.2047035]
 [1.1935465]]
886 Cost:  0.7028233 
Prediction:
 [[1.6311247]
 [1.1668475]
 [1.2406396]
 [1.3441979]
 [1.3066468]
 [1.3417964]
 [1.2046841]
 [1.1935273]]
887 Cost:  0.702783 
Prediction:
 [[1.6310899]
 [1.1668128]
 [1.2406101]
 [1.3441741]
 [1.3066195]
 [1.3417699]
 [1.2046648]
 [1.193508 ]]
888 Cost:  0.7027427 
Prediction:
 [[1.6310551]
 [1.1667781]
 [1.2405806]
 [1.3441505]
 [1.3065922]
 [1.3417434]
 [1.2046455]
 [1.1934887]]
889 Cost:  0.7027025 

1177 Cost:  0.6912291 
Prediction:
 [[1.6210575]
 [1.1568072]
 [1.2321018]
 [1.3373569]
 [1.2987528]
 [1.3341279]
 [1.19909  ]
 [1.1879482]]
1178 Cost:  0.6911897 
Prediction:
 [[1.6210229]
 [1.1567727]
 [1.2320726]
 [1.3373334]
 [1.2987258]
 [1.3341017]
 [1.1990709]
 [1.1879292]]
1179 Cost:  0.69115025 
Prediction:
 [[1.6209886]
 [1.1567384]
 [1.2320434]
 [1.3373101]
 [1.2986988]
 [1.3340755]
 [1.1990517]
 [1.1879101]]
1180 Cost:  0.6911107 
Prediction:
 [[1.620954 ]
 [1.156704 ]
 [1.2320141]
 [1.3372866]
 [1.2986717]
 [1.3340492]
 [1.1990325]
 [1.1878909]]
1181 Cost:  0.6910713 
Prediction:
 [[1.6209197]
 [1.1566696]
 [1.2319849]
 [1.3372631]
 [1.2986448]
 [1.3340229]
 [1.1990135]
 [1.1878718]]
1182 Cost:  0.6910317 
Prediction:
 [[1.6208851]
 [1.1566353]
 [1.2319556]
 [1.3372397]
 [1.2986177]
 [1.3339967]
 [1.1989943]
 [1.1878526]]
1183 Cost:  0.69099224 
Prediction:
 [[1.6208508]
 [1.156601 ]
 [1.2319264]
 [1.3372163]
 [1.2985907]
 [1.3339704]
 [1.1989751]
 [1.1878335]]
1184 Cost: 

1476 Cost:  0.6795775 
Prediction:
 [[1.6108341]
 [1.1466088]
 [1.2234282]
 [1.3304052]
 [1.2907329]
 [1.3263367]
 [1.1934028]
 [1.1822755]]
1477 Cost:  0.6795391 
Prediction:
 [[1.6108003]
 [1.146575 ]
 [1.2233995]
 [1.3303821]
 [1.2907063]
 [1.3263109]
 [1.1933838]
 [1.1822566]]
1478 Cost:  0.6795005 
Prediction:
 [[1.6107662]
 [1.1465411]
 [1.2233707]
 [1.3303591]
 [1.2906796]
 [1.326285 ]
 [1.193365 ]
 [1.1822377]]
1479 Cost:  0.6794621 
Prediction:
 [[1.6107323]
 [1.1465071]
 [1.223342 ]
 [1.330336 ]
 [1.290653 ]
 [1.3262591]
 [1.193346 ]
 [1.1822189]]
1480 Cost:  0.6794236 
Prediction:
 [[1.6106982]
 [1.1464733]
 [1.2233131]
 [1.3303128]
 [1.2906263]
 [1.3262333]
 [1.1933272]
 [1.1822001]]
1481 Cost:  0.6793852 
Prediction:
 [[1.6106644]
 [1.1464393]
 [1.2232842]
 [1.3302898]
 [1.2905997]
 [1.3262074]
 [1.1933084]
 [1.1821812]]
1482 Cost:  0.6793466 
Prediction:
 [[1.6106303]
 [1.1464055]
 [1.2232554]
 [1.3302667]
 [1.290573 ]
 [1.3261814]
 [1.1932894]
 [1.1821624]]
1483 Cost:  0

1745 Cost:  0.6693189 
Prediction:
 [[1.6017437]
 [1.1375381]
 [1.2157122]
 [1.3242189]
 [1.2835975]
 [1.3194046]
 [1.1883384]
 [1.1772237]]
1746 Cost:  0.66928124 
Prediction:
 [[1.6017101]
 [1.1375046]
 [1.2156837]
 [1.324196 ]
 [1.2835711]
 [1.319379 ]
 [1.1883197]
 [1.1772051]]
1747 Cost:  0.6692435 
Prediction:
 [[1.6016766]
 [1.1374711]
 [1.2156552]
 [1.3241732]
 [1.2835448]
 [1.3193533]
 [1.188301 ]
 [1.1771864]]
1748 Cost:  0.66920584 
Prediction:
 [[1.601643 ]
 [1.1374376]
 [1.2156267]
 [1.3241503]
 [1.2835184]
 [1.3193278]
 [1.1882823]
 [1.1771677]]
1749 Cost:  0.6691681 
Prediction:
 [[1.6016095]
 [1.137404 ]
 [1.2155981]
 [1.3241274]
 [1.2834921]
 [1.3193021]
 [1.1882635]
 [1.177149 ]]
1750 Cost:  0.6691303 
Prediction:
 [[1.6015759]
 [1.1373706]
 [1.2155696]
 [1.3241045]
 [1.2834656]
 [1.3192766]
 [1.1882448]
 [1.1771303]]
1751 Cost:  0.66909266 
Prediction:
 [[1.6015422]
 [1.137337 ]
 [1.2155411]
 [1.3240817]
 [1.2834393]
 [1.319251 ]
 [1.1882261]
 [1.1771116]]
1752 Cost:

1932 Cost:  0.6623043 
Prediction:
 [[1.5954788]
 [1.1312852]
 [1.2103921]
 [1.3199521]
 [1.2786775]
 [1.3146244]
 [1.1848438]
 [1.1737373]]
1933 Cost:  0.662267 
Prediction:
 [[1.5954454]
 [1.1312518]
 [1.2103639]
 [1.3199295]
 [1.2786512]
 [1.314599 ]
 [1.1848252]
 [1.1737187]]
1934 Cost:  0.66222984 
Prediction:
 [[1.595412 ]
 [1.1312186]
 [1.2103355]
 [1.3199068]
 [1.2786251]
 [1.3145735]
 [1.1848066]
 [1.1737001]]
1935 Cost:  0.66219264 
Prediction:
 [[1.5953786]
 [1.1311853]
 [1.2103072]
 [1.3198841]
 [1.2785989]
 [1.3145481]
 [1.184788 ]
 [1.1736816]]
1936 Cost:  0.6621555 
Prediction:
 [[1.5953454]
 [1.131152 ]
 [1.2102789]
 [1.3198614]
 [1.2785728]
 [1.3145227]
 [1.1847694]
 [1.1736631]]
1937 Cost:  0.6621183 
Prediction:
 [[1.595312 ]
 [1.1311188]
 [1.2102506]
 [1.3198388]
 [1.2785466]
 [1.3144974]
 [1.1847508]
 [1.1736445]]
1938 Cost:  0.66208124 
Prediction:
 [[1.5952786]
 [1.1310855]
 [1.2102224]
 [1.319816 ]
 [1.2785205]
 [1.3144718]
 [1.1847323]
 [1.1736261]]
1939 Cost: 