In [1]:
import tensorflow as tf

In [2]:
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# Evaluate our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

In [3]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# learning rate=1.5, 1e-10
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [5]:
prediction = tf.arg_max(hypothesis, 1)

In [6]:
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [7]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
    
    # predict
    print("Prediction: ", sess.run(prediction, feed_dict={X: x_test}))
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 2.6981497 [[ 1.2566587   1.0150052  -0.69337034]
 [ 0.77840525  1.5293808  -0.86674696]
 [-0.05244724 -0.7780307   1.6624348 ]]
1 2.2450213 [[ 1.2405697   1.0175322  -0.6798084 ]
 [ 0.748962    1.5345765  -0.8424994 ]
 [-0.06933516 -0.73098826  1.6322803 ]]
2 2.2094631 [[ 1.2327857   1.0121218  -0.6666138 ]
 [ 0.7645627   1.4960357  -0.8195592 ]
 [-0.04440077 -0.72417873  1.6005365 ]]
3 2.1759553 [[ 1.2189399   1.0121645  -0.6528107 ]
 [ 0.7474947   1.4876846  -0.79414016]
 [-0.05000756 -0.6899128   1.5718774 ]]
4 2.1437411 [[ 1.209374    1.0081931  -0.63927346]
 [ 0.7536093   1.4572607  -0.7698308 ]
 [-0.03400097 -0.676064    1.542022  ]]
5 2.112096 [[ 1.1966355   1.0071304  -0.6254722 ]
 [ 0.7425847   1.4430114  -0.74455684]
 [-0.03397419 -0.64760405  1.5135353 ]]
6 2.0808818 [[ 1.1862183   1.0039014  -0.611826  ]
 [ 0.7441277   1.4169016  -0.71999   ]
 [-0.02221621 -0.6302126   1.4843858 ]]
7 2.049969 [[ 1.1740613   1.0022804  -0.5980481 ]
 [ 0.73625934  1.3997947  -0.6950147 ]
 [